version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpass"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data: